const ASSETS={BTC:{name:'Bitcoin',price:78520.52,change:1.5,icon:'btc',major:true},ETH:{name:'Ethereum',price:2462.65,change:1.2,icon:'eth',major:true},SOL:{name:'Solana',price:98.40,change:2.4,icon:'sol',major:true},XRP:{name:'XRP',price:1.40,change:-3.68,icon:'xrp',major:true},ADA:{name:'Cardano',price:.203,change:1.39,icon:'ada',major:true},BNB:{name:'BNB',price:641.20,change:.82,icon:'bnb',major:true},DOGE:{name:'Dogecoin',price:.178,change:-1.72,icon:'doge',major:false},PEPE:{name:'Pepe',price:.0000124,change:4.85,icon:'pepe',major:false}};
const KEY='kereos-v13-state';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{cash:10000,positions:{},orders:[],watch:['BTC','ETH','SOL'],history:[],currency:'USD',theme:'dark',sound:true,animation:true};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(v){const c=state.currency;const symbols={USD:'$',INR:'₹',EUR:'€',GBP:'£'};let rate={USD:1,INR:88.2,EUR:.85,GBP:.73}[c];let n=v*rate;return symbols[c]+n.toLocaleString(undefined,{minimumFractionDigits:n<1?4:2,maximumFractionDigits:n<1?6:2})}
function asset(k){return ASSETS[k]}
function nav(){const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===path))}
function shell(){document.querySelector('#app').innerHTML=`<div class="ambient"><div class="grid"></div></div><div class="layout"><aside class="sidebar"><div class="brand"><img src="assets/logo.svg" alt="KEREOS logo"><div><h1>KEREOS</h1><small>THE FAST MONEY TERMINAL</small></div></div><nav class="nav">${[['index.html','⌂','Dashboard'],['markets.html','▦','Markets'],['portfolio.html','▤','Portfolio'],['orders.html','◇','Orders'],['watchlist.html','★','Watchlist'],['analytics.html','◉','Analytics'],['challenges.html','ϟ','Challenges'],['news.html','●','News'],['settings.html','⚙','Settings']].map(x=>`<a href="${x[0]}"><span class="ico">${x[1]}</span><span>${x[2]}</span></a>`).join('')}</nav><div class="status"><span class="dot"></span><b>KEREOS V13</b><div style="font-size:11px;color:var(--muted);margin-top:4px">Live demo engine</div></div></aside><main class="main"><header class="topbar"><button class="btn mobile-menu" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><div class="ticker" id="ticker"></div><div class="top-actions"><span class="pill">● DEMO</span><select id="currencySelect" onchange="setCurrency(this.value)"><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option></select><button class="btn" onclick="location.href='settings.html'">⚙</button></div></header><div id="content"></div></main></div><div id="modalRoot"></div>`;nav();renderTicker();setInterval(tickMarket,2200);}
function renderTicker(){const t=document.querySelector('#ticker');if(!t)return;t.innerHTML=['BTC','ETH','SOL','XRP','ADA','BNB'].map(k=>`<span class="tick"><b>${k}</b> ${money(asset(k).price)} <strong class="${asset(k).change>=0?'up':'down'}">${asset(k).change>=0?'+':''}${asset(k).change.toFixed(2)}%</strong></span>`).join('');const c=document.querySelector('#currencySelect');if(c)c.value=state.currency}
function tickMarket(){Object.keys(ASSETS).forEach(k=>{let a=ASSETS[k];let drift=(Math.random()-.48)*.0018;a.price=Math.max(a.price*(1+drift),a.price*.2);a.change+=drift*100;});Object.entries(state.positions).forEach(([k,p])=>{p.market=ASSETS[k].price});state.history.push({t:Date.now(),v:portfolioValue()});if(state.history.length>240)state.history.shift();save();renderTicker();if(window.pageRender)window.pageRender()}
function portfolioValue(){return state.cash+Object.entries(state.positions).reduce((s,[k,p])=>s+p.qty*ASSETS[k].price,0)}
function invested(){return Object.entries(state.positions).reduce((s,[k,p])=>s+p.qty*p.avg,0)}
function toast(msg){let d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2500)}
function beep(type){if(!state.sound)return;try{let C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=type==='buy'?720:type==='sell'?420:260;o.type='sine';g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.06,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.16);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.18)}catch(e){}}
function setCurrency(c){state.currency=c;save();window.pageRender?.();renderTicker()}
function trade(k,side){const a=asset(k),p=state.positions[k]||{qty:0,avg:0,buys:[]};let selected=side==='sell'?100:null;document.querySelector('#modalRoot').innerHTML=`<div class="modal-back show" onclick="if(event.target===this)this.remove()"><div class="modal"><div class="asset-head"><img class="coin-logo" src="assets/crypto/${a.icon}.svg"><div><div class="asset-name">${a.name}</div><div class="asset-symbol">${k} · Demo execution</div></div></div><div class="bigprice">${money(a.price)}</div><div class="chart-wrap" style="height:230px;margin-bottom:14px"><canvas id="tradeChart"></canvas></div><div class="trade-row"><button class="btn buy" onclick="openTrade('${k}','buy')">BUY</button><button class="btn sell" onclick="openTrade('${k}','sell')">SELL</button></div><label class="label" style="display:block;margin-top:16px">Amount (base currency)</label><input id="tradeAmount" type="number" min="0" step="any" value="${side==='buy'?Math.min(state.cash,a.price).toFixed(2):(p.qty*a.price).toFixed(2)}" style="width:100%;margin-top:7px"><div id="sellSeg" style="display:${side==='sell'?'block':'none'}"><div class="label" style="margin-top:15px">Sell position</div><div class="seg"><button onclick="selectPct(10)">Sell 10%</button><button onclick="selectPct(50)">Sell 50%</button><button onclick="selectPct(100)" class="selected">Sell 100%</button></div></div><div class="sub" id="tradeInfo">${side==='sell'?`Available: ${p.qty.toFixed(8)} ${k}`:'Enter the amount you want to spend.'}</div><div class="modal-actions" style="margin-top:18px"><button class="btn" onclick="document.querySelector('.modal-back').remove()">Cancel</button><button class="btn primary" onclick="executeTrade('${k}','${side}')">Place ${side} order</button></div></div></div>`;window.currentSide=side;window.currentPct=100;setTimeout(()=>candles(document.querySelector('#tradeChart'),k),20)}
function openTrade(k,side){trade(k,side)}
function selectPct(n){window.currentPct=n;document.querySelectorAll('.seg button').forEach(b=>b.classList.toggle('selected',b.textContent.includes(n+'%')));let k=document.querySelector('.asset-symbol').textContent.split(' ·')[0];let p=state.positions[k];if(p)document.querySelector('#tradeAmount').value=(p.qty*ASSETS[k].price*n/100).toFixed(2)}
function executeTrade(k,side){const a=asset(k),amount=Math.max(0,Number(document.querySelector('#tradeAmount').value)||0);if(side==='buy'){if(amount<=0||amount>state.cash){toast('Insufficient cash or invalid amount');beep('err');return}let qty=amount/a.price,p=state.positions[k]||{qty:0,avg:0,buys:[]};p.avg=(p.qty*p.avg+amount)/(p.qty+qty);p.qty+=qty;p.buys.push({price:a.price,qty,time:Date.now()});state.positions[k]=p;state.cash-=amount;record(k,'BUY',a.price,qty);toast(`Bought ${qty.toFixed(8)} ${k} at ${money(a.price)}`);beep('buy')}else{let p=state.positions[k];if(!p||p.qty<=0){toast('No position to sell');beep('err');return}let qty=p.qty*(window.currentPct||100)/100;if(amount>0){qty=Math.min(qty,amount/a.price)}if(qty<=0){toast('Invalid sell amount');return}state.cash+=qty*a.price;p.qty-=qty;record(k,'SELL',a.price,qty);if(p.qty<1e-12)delete state.positions[k];else state.positions[k]=p;toast(`Sold ${qty.toFixed(8)} ${k} at ${money(a.price)}`);beep('sell')}save();document.querySelector('.modal-back')?.remove();window.pageRender?.()}
function record(k,side,price,qty){state.orders.unshift({id:'K'+Date.now(),time:new Date().toLocaleTimeString(),asset:k,side,price,qty,value:price*qty});if(state.orders.length>200)state.orders.pop()}
function canvasLine(canvas,points,color){const c=canvas.getContext('2d'),r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;c.scale(d,d);c.clearRect(0,0,r.width,r.height);c.strokeStyle='rgba(255,255,255,.07)';c.lineWidth=1;for(let y=40;y<r.height;y+=r.height/4){c.beginPath();c.moveTo(0,y);c.lineTo(r.width,y);c.stroke()}let min=Math.min(...points),max=Math.max(...points),pad=(max-min)*.12||1;c.strokeStyle=color;c.shadowColor=color;c.shadowBlur=12;c.lineWidth=2.5;c.beginPath();points.forEach((v,i)=>{let x=i*(r.width/(points.length-1)),y=r.height-25-((v-(min-pad))/(max-min+2*pad))*(r.height-45);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.shadowBlur=0}
function chart(canvas,k){let a=ASSETS[k],base=a.price;let pts=Array.from({length:46},(_,i)=>base*(1+Math.sin(i*.43+k.length)*.018+(Math.random()-.5)*.012));pts.push(base);canvasLine(canvas,pts,a.change>=0?'#38f59a':'#ff536b')}
function candles(canvas,k){let a=ASSETS[k],r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;let c=canvas.getContext('2d');c.scale(d,d);let W=r.width,H=r.height;c.clearRect(0,0,W,H);c.strokeStyle='rgba(255,255,255,.08)';c.lineWidth=1;for(let y=35;y<H;y+=H/5){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}let n=58,vals=[],v=a.price*.98;for(let i=0;i<n;i++){let o=v,close=o*(1+(Math.random()-.47)*.008),hi=Math.max(o,close)*(1+Math.random()*.006),lo=Math.min(o,close)*(1-Math.random()*.006);vals.push({o,close,hi,lo});v=close}let min=Math.min(...vals.map(x=>x.lo)),max=Math.max(...vals.map(x=>x.hi)),scale=(H-50)/(max-min);vals.forEach((x,i)=>{let xx=15+i*((W-30)/n),up=x.close>=x.o,col=up?'#38f59a':'#ff536b';let y=o=>H-25-(o-min)*scale;c.strokeStyle=col;c.lineWidth=1.5;c.beginPath();c.moveTo(xx,y(x.hi));c.lineTo(xx,y(x.lo));c.stroke();c.fillStyle=col;let top=y(Math.max(x.o,x.close)),bh=Math.max(2,Math.abs(y(x.o)-y(x.close)));c.fillRect(xx-3,top,6,bh)});let pos=state.orders.filter(o=>o.asset===k).slice(0,30);pos.forEach(o=>{let y=H-25-(o.price-min)*scale;let col=o.side==='BUY'?'#38f59a':'#ff536b';c.fillStyle=col;c.beginPath();c.arc(W-45,y,5,0,Math.PI*2);c.fill();c.font='11px system-ui';c.fillText(o.side,W-40,y+4)})}
window.KEREOS={ASSETS,state,trade,candles,chart,money,portfolioValue,invested};
