const API='https://api.binance.com/api/v3/ticker/24hr';
const STORAGE='kereos_v7_account';
const ASSETS={
 BTC:{symbol:'BTCUSDT',name:'Bitcoin',ticker:'BTC',cls:'btc',icon:'₿',fallback:78644.03},
 ETH:{symbol:'ETHUSDT',name:'Ethereum',ticker:'ETH',cls:'eth',icon:'Ξ',fallback:2462.65},
 SOL:{symbol:'SOLUSDT',name:'Solana',ticker:'SOL',cls:'sol',icon:'S',fallback:188.40},
 XRP:{symbol:'XRPUSDT',name:'XRP',ticker:'XRP',cls:'xrp',icon:'X',fallback:1.398},
 ADA:{symbol:'ADAUSDT',name:'Cardano',ticker:'ADA',cls:'ada',icon:'A',fallback:.2028},
 DOGE:{symbol:'DOGEUSDT',name:'Dogecoin',ticker:'DOGE',cls:'doge',icon:'Ð',fallback:.213},
 SHIB:{symbol:'SHIBUSDT',name:'Shiba Inu',ticker:'SHIB',cls:'shib',icon:'S',fallback:.0000124},
 PEPE:{symbol:'PEPEUSDT',name:'Pepe',ticker:'PEPE',cls:'pepe',icon:'🐸',fallback:.0000091}
};
const MEMES=new Set(['DOGE','SHIB','PEPE']);
let prices={},priceMeta={online:false,updated:0};
let account=loadAccount();let trade={asset:'BTC',side:'buy'};
function blankAccount(){return{cash:10000,positions:{},orders:[],realizedPnl:0,fees:0,createdAt:Date.now()}}
function loadAccount(){try{const a=JSON.parse(localStorage.getItem(STORAGE));if(a&&typeof a.cash==='number'&&a.positions&&Array.isArray(a.orders))return a}catch(e){}return blankAccount()}
function saveAccount(){localStorage.setItem(STORAGE,JSON.stringify(account))}
function money(n){const x=Number(n)||0;return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Math.abs(x)<1?6:2}).format(x)}
function qtyFmt(n){const x=Number(n)||0;return x<1?x.toFixed(8).replace(/0+$/,'').replace(/\.$/,''):x.toFixed(4).replace(/0+$/,'').replace(/\.$/,'')}
function currentPrice(a){return Number(prices[a]?.price||ASSETS[a].fallback)}
function currentChange(a){return Number(prices[a]?.change||0)}
function positionValue(a){const p=account.positions[a];return p?p.qty*currentPrice(a):0}
function investedValue(){return Object.values(account.positions).reduce((s,p)=>s+p.costBasis,0)}
function totalValue(){return account.cash+Object.keys(account.positions).reduce((s,a)=>s+positionValue(a),0)}
function unrealizedPnl(){return Object.entries(account.positions).reduce((s,[a,p])=>s+positionValue(a)-p.costBasis,0)}
async function fetchPrices(){
 try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw 0;const rows=await r.json();const wanted=new Set(Object.values(ASSETS).map(x=>x.symbol));rows.filter(x=>wanted.has(x.symbol)).forEach(x=>{const a=Object.keys(ASSETS).find(k=>ASSETS[k].symbol===x.symbol);prices[a]={price:Number(x.lastPrice),change:Number(x.priceChangePercent),volume:Number(x.quoteVolume)}});if(Object.keys(prices).length<6)throw 0;priceMeta={online:true,updated:Date.now()};localStorage.setItem('kereos_last_prices',JSON.stringify(prices))}
 catch(e){try{const cached=JSON.parse(localStorage.getItem('kereos_last_prices')||'{}');prices=Object.keys(cached).length?cached:Object.fromEntries(Object.entries(ASSETS).map(([a,x])=>[a,{price:x.fallback,change:0,volume:0}]))}catch(_){prices=Object.fromEntries(Object.entries(ASSETS).map(([a,x])=>[a,{price:x.fallback,change:0,volume:0}]))}priceMeta={online:false,updated:Date.now()}}
 renderAll()
}
function statusHtml(){return `<div class="statusline"><span class="dot ${priceMeta.online?'':'off'}"></span>${priceMeta.online?'Live Binance market feed':'Using last saved market prices'}${priceMeta.updated?' · '+new Date(priceMeta.updated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</div>`}
function nav(){const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===page))}
function common(){nav();document.querySelectorAll('[data-cash]').forEach(x=>x.textContent=money(account.cash));document.querySelectorAll('[data-total]').forEach(x=>x.textContent=money(totalValue()));document.querySelectorAll('[data-invested]').forEach(x=>x.textContent=money(investedValue()));document.querySelectorAll('[data-pnl]').forEach(x=>{const n=unrealizedPnl();x.textContent=(n>=0?'+':'')+money(n);x.classList.toggle('green',n>=0);x.classList.toggle('red',n<0)});document.querySelectorAll('[data-feed]').forEach(x=>x.innerHTML=statusHtml())}
function renderMarkets(){const grid=document.getElementById('coinGrid');if(!grid)return;const q=(document.getElementById('search')?.value||'').trim().toLowerCase();const tab=document.querySelector('.tab.active')?.dataset.tab||'all';grid.innerHTML=Object.entries(ASSETS).filter(([a,c])=>!q||(a+c.name+c.ticker).toLowerCase().includes(q)).filter(([a])=>tab==='all'||(tab==='meme'?MEMES.has(a):!MEMES.has(a))).map(([a,c])=>{const p=currentPrice(a),ch=currentChange(a),up=ch>=0;return `<article class="card coin-card"><div class="coin-top"><div class="asset"><div class="coin ${c.cls}">${c.icon}</div><div><b>${c.name}</b><small>${c.ticker} · CRYPTO</small></div></div><span class="tag ${up?'up':'down'}">${up?'▲':'▼'} ${Math.abs(ch).toFixed(2)}%</span></div><div class="price">${money(p)}</div><div class="price-sub ${up?'green':'red'}">${up?'+':''}${ch.toFixed(2)}% today</div><div class="price-sub" style="margin-top:8px">24h volume ${prices[a]?.volume?money(prices[a].volume):'—'}</div><div class="coin-actions"><button class="btn buy" onclick="openTrade('${a}','buy')">Buy ${a}</button><button class="btn sell" onclick="openTrade('${a}','sell')">Sell</button></div>${statusHtml()}</article>`}).join('')||`<div class="card empty">No assets match your search.</div>`}
function openTrade(asset,side){trade={asset,side};const modal=document.getElementById('tradeModal');if(!modal)return;modal.classList.add('show');document.getElementById('tradeName').textContent=ASSETS[asset].name;document.getElementById('tradeTicker').textContent=asset;document.getElementById('tradePrice').textContent=money(currentPrice(asset));document.getElementById('tradeAmount').value='100';setTradeSide(side)}
function closeTrade(){document.getElementById('tradeModal')?.classList.remove('show')}
function setTradeSide(side){trade.side=side;document.getElementById('buyTab')?.classList.toggle('active',side==='buy');document.getElementById('sellTab')?.classList.toggle('active',side==='sell');const a=trade.asset,p=account.positions[a],max=p?positionValue(a):0;const m=document.getElementById('maxSell');if(m)m.textContent=side==='sell'&&p?`You can sell up to ${money(max)} (${qtyFmt(p.qty)} ${a})`:side==='sell'?'You do not own this asset.':'';updateEstimate()}
function setQuick(n){document.getElementById('tradeAmount').value=n;updateEstimate()}
function updateEstimate(){const amount=Math.max(0,Number(document.getElementById('tradeAmount')?.value||0)),a=trade.asset,p=currentPrice(a),qty=p?amount/p:0,fee=amount*.001,holding=account.positions[a],max=holding?holding.qty*p:0;document.getElementById('estQty').textContent=qtyFmt(qty)+' '+a;document.getElementById('estFee').textContent=money(fee);document.getElementById('estTotal').textContent=trade.side==='buy'?money(amount+fee):money(Math.max(0,amount-fee));let text='';if(trade.side==='buy'&&amount+fee>account.cash)text=`Not enough cash. Available: ${money(account.cash)}.`;if(trade.side==='sell'&&(!holding||holding.qty<=0))text=`You don't own ${a}. Buy it first.`;if(trade.side==='sell'&&amount>max+0.000001)text=`Maximum sell value is ${money(max)}.`;document.getElementById('tradeWarn').textContent=text;document.getElementById('confirmTrade').disabled=!!text||amount<=0}
function executeTrade(){const a=trade.asset,amount=Number(document.getElementById('tradeAmount').value),price=currentPrice(a),fee=amount*.001;if(!Number.isFinite(amount)||amount<=0)return toast('Enter a valid USD amount.','error');if(trade.side==='buy'){const total=amount+fee;if(total>account.cash+1e-9)return toast('Insufficient demo cash.','error');const qty=amount/price,old=account.positions[a]||{qty:0,costBasis:0,realized:0};old.qty+=qty;old.costBasis+=total;account.positions[a]=old;account.cash-=total;account.fees+=fee;addOrder('BUY',a,qty,amount,price,fee);toast(`Bought ${qtyFmt(qty)} ${a} for ${money(amount)}.`)}else{const p=account.positions[a];if(!p||p.qty<=0)return toast(`You don't own ${a}.`,'error');const maxValue=p.qty*price;if(amount>maxValue+1e-8)return toast(`You can sell up to ${money(maxValue)}.`,'error');const qty=amount/price,basis=qty*(p.costBasis/p.qty),proceeds=amount-fee,realized=proceeds-basis;p.qty-=qty;p.costBasis-=basis;account.cash+=proceeds;account.fees+=fee;account.realizedPnl+=realized;if(p.qty<1e-10||p.costBasis<1e-8)delete account.positions[a];addOrder('SELL',a,qty,amount,price,fee);toast(`Sold ${qtyFmt(qty)} ${a} for ${money(amount)}.`)}saveAccount();closeTrade();renderAll()}
function addOrder(side,a,qty,amount,price,fee){account.orders.unshift({id:String(Date.now()+Math.random()),side,asset:a,qty,amount,price,fee,time:Date.now()});account.orders=account.orders.slice(0,60)}
function addBalance(){const value=Number(prompt('Add demo balance (USD):','1000'));if(!Number.isFinite(value)||value<=0)return;account.cash+=value;account.orders.unshift({id:String(Date.now()),side:'DEPOSIT',asset:'USD',qty:0,amount:value,price:1,fee:0,time:Date.now()});saveAccount();renderAll();toast(`Added ${money(value)} demo balance.`)}
function resetAccount(){if(!confirm('Reset the demo account to $10,000 and remove all positions?'))return;account=blankAccount();saveAccount();renderAll();toast('Demo account reset.')}
function renderPortfolio(){if(!document.getElementById('holdings'))return;const rows=document.getElementById('holdings'),entries=Object.entries(account.positions);rows.innerHTML=entries.length?entries.map(([a,p])=>{const c=ASSETS[a],value=p.qty*currentPrice(a),gain=value-p.costBasis,avg=p.qty?p.costBasis/p.qty:0;return `<tr><td><div class="asset"><div class="coin ${c.cls}">${c.icon}</div><div><b>${a}</b><small>${c.name}</small></div></div></td><td>${qtyFmt(p.qty)}</td><td>${money(avg)}</td><td>${money(currentPrice(a))}</td><td>${money(value)}</td><td class="${gain>=0?'green':'red'}">${gain>=0?'+':''}${money(gain)}</td><td><button class="btn sell" onclick="openTrade('${a}','sell')">Sell</button></td></tr>`}).join(''):`<tr><td colspan="7" class="empty">No positions yet. Open Markets and make a demo trade.</td></tr>`;const hist=document.getElementById('history');if(hist)hist.innerHTML=account.orders.length?account.orders.slice(0,10).map(o=>`<tr><td>${new Date(o.time).toLocaleString()}</td><td class="${o.side==='BUY'?'green':o.side==='SELL'?'red':'muted'}">${o.side}</td><td>${o.asset}</td><td>${o.side==='SELL'?'-':o.side==='DEPOSIT'?'+':''}${money(o.amount)}</td><td>${o.side==='DEPOSIT'?'Balance added':'Filled'}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No activity yet.</td></tr>`;document.getElementById('realized')?.replaceChildren(document.createTextNode((account.realizedPnl>=0?'+':'')+money(account.realizedPnl)));document.getElementById('fees')?.replaceChildren(document.createTextNode(money(account.fees)));drawChart()}
function drawChart(){const canvas=document.getElementById('performanceChart');if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),W=Math.max(320,rect.width),H=250;canvas.width=W*dpr;canvas.height=H*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,W,H);ctx.strokeStyle='#202640';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,H*i/5);ctx.lineTo(W,H*i/5);ctx.stroke()}const base=totalValue(),seed=(account.orders.length*17+Math.floor(base))%97,pts=[];for(let i=0;i<50;i++)pts.push(base+Math.sin((i+seed)*.43)*base*.006+Math.sin(i*.12)*base*.004);const min=Math.min(...pts),max=Math.max(...pts);ctx.beginPath();pts.forEach((v,i)=>{const x=i*(W/(pts.length-1)),y=H-18-((v-min)/(max-min||1))*(H-35);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#9a70ff';ctx.lineWidth=2.5;ctx.stroke()}
function renderDashboard(){const x=document.getElementById('dashInvested');if(x)x.textContent=money(investedValue());const y=document.getElementById('dashRealized');if(y)y.textContent=(account.realizedPnl>=0?'+':'')+money(account.realizedPnl);renderMarkets();drawChart()}
function startChallenge(name,target,hours){if(account.challenge)return toast('Finish your current challenge first.','error');account.challenge={name,target,startCash:account.cash,start:Date.now(),hours};saveAccount();renderChallenges();toast('Challenge started.')}
function renderChallenges(){const box=document.getElementById('challengeStatus');if(!box)return;if(!account.challenge){box.innerHTML='<b>No active challenge</b><div class="muted" style="font-size:11px;margin-top:6px">Choose a challenge below to begin.</div>';return}const c=account.challenge,elapsed=(Date.now()-c.start)/3600000,remain=Math.max(0,c.hours-elapsed),pct=Math.min(100,Math.max(0,(account.cash-c.startCash)/(c.target-c.startCash)*100)),done=account.cash>=c.target;box.innerHTML=`<b>${c.name}</b><div class="muted" style="font-size:11px;margin:7px 0">Target ${money(c.target)} cash · ${remain.toFixed(1)}h remaining</div><div class="progress"><span style="width:${pct}%"></span></div><div style="font-size:10px;margin-top:7px">Start ${money(c.startCash)} · Current ${money(account.cash)}</div>${done?'<div class="green" style="margin-top:8px;font-size:11px">🏆 Challenge complete!</div>':''}`}
function toast(message,type='ok'){const x=document.getElementById('toast');if(!x)return;x.textContent=message;x.className='toast show '+(type==='error'?'error':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),3200)}
function renderAll(){common();renderMarkets();renderPortfolio();renderDashboard();renderChallenges()}
document.addEventListener('input',e=>{if(e.target.id==='search')renderMarkets();if(e.target.id==='tradeAmount')updateEstimate()});
document.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderMarkets()}if(e.target.id==='tradeModal'&&e.target===e.currentTarget)closeTrade()});
window.addEventListener('resize',drawChart);window.addEventListener('load',()=>{renderAll();fetchPrices();setInterval(fetchPrices,20000);setInterval(renderAll,30000)});
