/* KEREOS V12 — single shared demo engine */
const ASSETS={
 BTC:{name:'Bitcoin',sym:'BTC',price:78644,change:1.50,kind:'Major',icon:'₿',cls:'btc'},
 ETH:{name:'Ethereum',sym:'ETH',price:2462.65,change:1.12,kind:'Major',icon:'◆',cls:'eth'},
 XRP:{name:'XRP',sym:'XRP',price:1.40,change:-3.68,kind:'Major',icon:'X',cls:'xrp'},
 ADA:{name:'Cardano',sym:'ADA',price:.203,change:1.39,kind:'Major',icon:'A',cls:'ada'},
 SOL:{name:'Solana',sym:'SOL',price:198.40,change:2.41,kind:'Major',icon:'≋',cls:'sol'},
 DOGE:{name:'Dogecoin',sym:'DOGE',price:.224,change:-2.06,kind:'Meme',icon:'Ð',cls:'doge'},
 PEPE:{name:'Pepe',sym:'PEPE',price:.0000118,change:4.22,kind:'Meme',icon:'🐸',cls:'pepe'},
 BNB:{name:'BNB',sym:'BNB',price:691.25,change:.84,kind:'Major',icon:'◆',cls:'bnb'}
};
const CURRENCIES={USD:{symbol:'$',rate:1},INR:{symbol:'₹',rate:83.9},EUR:{symbol:'€',rate:.86},GBP:{symbol:'£',rate:.74},AED:{symbol:'د.إ',rate:3.67},JPY:{symbol:'¥',rate:156.2}};
const page=location.pathname.split('/').pop()||'index.html';
const state=JSON.parse(localStorage.getItem('kereosV12')||'null')||{cash:10000,positions:{},orders:[],watchlist:['BTC','ETH','SOL'],currency:'USD',theme:'dark',sound:true,animation:true};
function save(){localStorage.setItem('kereosV12',JSON.stringify(state));}
function money(v){const c=CURRENCIES[state.currency]; return c.symbol+(v*c.rate).toLocaleString(undefined,{minimumFractionDigits:v<1?4:2,maximumFractionDigits:v<1?6:2});}
function assetIcon(sym){const a=ASSETS[sym]||ASSETS.BTC;return `<span class="coin ${a.cls}">${a.icon}</span>`}
function shell(active){
return `<div class="aurora"></div><div class="grid-bg"></div><aside class="sidebar"><div class="brand"><img src="kereos-logo.svg"><div><b>KEREOS</b><small>THE FAST MONEY TERMINAL</small></div></div><div class="ticker">${Object.values(ASSETS).slice(0,6).map(a=>`<span>${a.sym} ${money(a.price)} <i class="${a.change>=0?'up':'down'}">${a.change>=0?'+':''}${a.change}%</i></span>`).join('')}</div><nav>${[['index.html','⌂','Dashboard'],['markets.html','▦','Markets'],['portfolio.html','▤','Portfolio'],['orders.html','◇','Orders'],['watchlist.html','☆','Watchlist'],['analytics.html','◉','Analytics'],['challenges.html','ϟ','Challenges'],['news.html','●','News'],['settings.html','⚙','Settings']].map(x=>`<a class="${active===x[2].toLowerCase()?'active':''}" href="${x[0]}"><span>${x[1]}</span>${x[2]}</a>`).join('')}</nav><div class="side-card"><strong>KEREOS V12</strong><p>Live demo market engine</p><div class="status"><b></b> Engine online</div></div></aside><main class="main"><header><div class="mobile-brand"><img src="kereos-logo.svg">KEREOS</div><div class="live"><b></b> DEMO · LIVE SIMULATION</div><select id="currency"><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option><option>AED</option><option>JPY</option></select><button class="iconbtn" id="themeBtn">☼</button><button class="iconbtn" id="soundBtn">🔊</button></header>`}
function closeShell(){return `</main>`}
function wireCommon(){
 const cur=document.getElementById('currency');if(cur){cur.value=state.currency;cur.onchange=()=>{state.currency=cur.value;save();location.reload()}}
 const tb=document.getElementById('themeBtn'); if(tb)tb.onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();document.body.classList.toggle('light',state.theme==='light')};
 const sb=document.getElementById('soundBtn'); if(sb)sb.onclick=()=>{state.sound=!state.sound;save();sb.textContent=state.sound?'🔊':'🔇'};
 document.body.classList.toggle('light',state.theme==='light');
 if(!state.animation)document.body.classList.add('no-animation');
}
function tone(type){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=type==='buy'?720:type==='sell'?420:180;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.07,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.17)}catch(e){}}
function simulatePrices(){Object.values(ASSETS).forEach(a=>{const drift=(Math.random()-.49)*.0018;a.price*=1+drift});}
function totalPositions(){return Object.entries(state.positions).reduce((s,[sym,p])=>s+p.qty*ASSETS[sym].price,0)}
function pnl(){return Object.entries(state.positions).reduce((s,[sym,p])=>s+(ASSETS[sym].price-p.avg)*p.qty,0)}
function execute(sym,side,qty){const a=ASSETS[sym];if(!a)return false;const px=a.price;
 if(side==='BUY'){const cost=px*qty;if(cost>state.cash+1e-8)return false;state.cash-=cost;const p=state.positions[sym]||{qty:0,avg:0};p.avg=(p.avg*p.qty+px*qty)/(p.qty+qty);p.qty+=qty;state.positions[sym]=p}
 else {const p=state.positions[sym];if(!p||p.qty<=0)return false;qty=Math.min(qty,p.qty);state.cash+=px*qty;p.qty-=qty;if(p.qty<1e-10)delete state.positions[sym]}
 state.orders.unshift({id:'KRS-'+Date.now().toString(36).toUpperCase(),time:new Date().toLocaleTimeString(),sym,side,qty,price:px,pnl:side==='SELL'?0:null});state.orders=state.orders.slice(0,100);save();tone(side==='BUY'?'buy':'sell');return true}
function chartHTML(sym='BTC',height=390){return `<div class="chart-wrap"><canvas id="tradeChart" height="${height}"></canvas><div class="chart-legend"><span><b class="dot updot"></b> Bullish</span><span><b class="dot downdot"></b> Bearish</span><span>● Buy</span><span>● Sell</span><em id="chartLive">LIVE</em></div></div>`}
function makeSeries(sym){let base=ASSETS[sym].price,arr=[],v=base*.965;for(let i=0;i<48;i++){let o=v,c=o*(1+(Math.random()-.47)*.014),h=Math.max(o,c)*(1+Math.random()*.008),l=Math.min(o,c)*(1-Math.random()*.008);arr.push({o,c,h,l});v=c}arr[arr.length-1].c=base;return arr}
function drawChart(sym='BTC',markers=[]){const cv=document.getElementById('tradeChart');if(!cv)return;const ctx=cv.getContext('2d'),dpr=devicePixelRatio||1,w=cv.clientWidth,h=cv.clientHeight;cv.width=w*dpr;cv.height=h*dpr;ctx.scale(dpr,dpr);let data=window.chartData||makeSeries(sym);window.chartData=data;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=i*h/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const min=Math.min(...data.map(x=>x.l)),max=Math.max(...data.map(x=>x.h)),pad=20;const y=v=>pad+(max-v)/(max-min)*(h-pad*2),cw=Math.max(6,(w-30)/data.length*.65),step=(w-30)/data.length;
 data.forEach((x,i)=>{let xx=15+i*step,up=x.c>=x.o;ctx.strokeStyle=up?'#39ff88':'#ff4d67';ctx.fillStyle=up?'#39ff88':'#ff4d67';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(xx+cw/2,y(x.h));ctx.lineTo(xx+cw/2,y(x.l));ctx.stroke();let top=y(Math.max(x.o,x.c)),bot=y(Math.min(x.o,x.c));ctx.fillRect(xx,top,cw,Math.max(2,bot-top));});
 markers.forEach(m=>{let i=Math.max(0,Math.min(data.length-1,m.index??data.length-1)),x=data[i],xx=15+i*step+cw/2,yy=y(x.c);ctx.beginPath();ctx.arc(xx,yy,6,0,Math.PI*2);ctx.fillStyle=m.side==='BUY'?'#39ff88':'#ff4d67';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.font='700 11px Inter';ctx.fillStyle=m.side==='BUY'?'#39ff88':'#ff4d67';ctx.fillText(m.side==='BUY'?'BUY':'SELL',xx+8,yy-8);});
}
function startLive(sym,markers){window.chartData=makeSeries(sym);drawChart(sym,markers);window._timer=setInterval(()=>{if(!state.animation)return;simulatePrices();const last=window.chartData.at(-1),o=last.c,c=o*(1+(Math.random()-.49)*.006);window.chartData.push({o,c,h:Math.max(o,c)*(1+Math.random()*.004),l:Math.min(o,c)*(1-Math.random()*.004)});window.chartData.shift();drawChart(sym,markers);const p=document.querySelector('.live-price');if(p)p.textContent=money(ASSETS[sym].price)},1200);window.addEventListener('resize',()=>drawChart(sym,markers))}
function tradeModal(sym){const p=state.positions[sym];return `<div class="modal hidden" id="tradeModal"><div class="modal-card"><button class="close" onclick="document.getElementById('tradeModal').classList.add('hidden')">×</button><div class="modal-head">${assetIcon(sym)}<div><h2>Trade ${ASSETS[sym].name}</h2><span>${sym} · Demo execution</span></div></div><div class="modal-price live-price">${money(ASSETS[sym].price)}</div><div class="order-side"><button class="buy active" data-side="BUY">BUY</button><button class="sell" data-side="SELL">SELL</button></div><label>Amount (quote currency)</label><input id="tradeAmount" type="number" min="1" step="1" value="100"><div id="sellOptions" class="sell-options hidden"><button data-pct="10">Sell 10%</button><button data-pct="50">Sell 50%</button><button data-pct="100">Sell 100%</button></div><div class="order-preview"><span>Available cash</span><b>${money(state.cash)}</b><span>Position</span><b>${p?`${p.qty.toFixed(6)} ${sym}`:'0'}</b></div><button id="confirmTrade" class="primary wide">Place demo order</button><p id="tradeMsg" class="muted"></p></div></div>`}
function openTrade(sym){document.body.insertAdjacentHTML('beforeend',tradeModal(sym));const m=document.getElementById('tradeModal');m.classList.remove('hidden');let side='BUY';const buttons=m.querySelectorAll('.order-side button');buttons.forEach(b=>b.onclick=()=>{side=b.dataset.side;buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('sellOptions').classList.toggle('hidden',side!=='SELL')});m.querySelectorAll('[data-pct]').forEach(b=>b.onclick=()=>{const p=state.positions[sym];if(p)document.getElementById('tradeAmount').value=(p.qty*(+b.dataset.pct)/100*ASSETS[sym].price).toFixed(2)});document.getElementById('confirmTrade').onclick=()=>{let amount=+document.getElementById('tradeAmount').value;if(!amount)return;let qty=side==='BUY'?amount/ASSETS[sym].price:amount/ASSETS[sym].price;const ok=execute(sym,side,qty);document.getElementById('tradeMsg').textContent=ok?`${side} executed at ${money(ASSETS[sym].price)}.`:`Order rejected — check your cash or position.`;if(ok)setTimeout(()=>location.reload(),600)} }
