
const coins=[
{id:"bitcoin",s:"BTC",name:"Bitcoin",cat:"Major",icon:"₿"},{id:"ethereum",s:"ETH",name:"Ethereum",cat:"Major",icon:"Ξ"},
{id:"solana",s:"SOL",name:"Solana",cat:"Major",icon:"S"},{id:"ripple",s:"XRP",name:"XRP",cat:"Major",icon:"X"},
{id:"cardano",s:"ADA",name:"Cardano",cat:"Major",icon:"A"},{id:"binancecoin",s:"BNB",name:"BNB",cat:"Major",icon:"B"},
{id:"dogecoin",s:"DOGE",name:"Dogecoin",cat:"Meme",icon:"Ð"},{id:"shiba-inu",s:"SHIB",name:"Shiba Inu",cat:"Meme",icon:"🐕"},
{id:"pepe",s:"PEPE",name:"Pepe",cat:"Meme",icon:"🐸"},{id:"bonk",s:"BONK",name:"Bonk",cat:"Meme",icon:"🐶"},
{id:"floki",s:"FLOKI",name:"Floki",cat:"Meme",icon:"🐺"},{id:"dogwifcoin",s:"WIF",name:"dogwifhat",cat:"Meme",icon:"🧢"}];
const fallback={bitcoin:78644,ethereum:2462,solana:141,ripple:1.398,cardano:.203,binancecoin:650,dogecoin:.1706,"shiba-inu":.0000167,pepe:.0000078,bonk:.000021,floki:.000081,dogwifcoin:.86};
let market={},hist={},activeFilter="All",selected=localStorage.getItem("kereos_selected")||"bitcoin",side="buy",sellPct=50;
let state=JSON.parse(localStorage.getItem("kereos_v10_ledger")||"null")||{cash:10000,positions:{},trades:[],xp:0};
function save(){localStorage.setItem("kereos_v10_ledger",JSON.stringify(state));localStorage.setItem("kereos_selected",selected)}
function c(id){return coins.find(x=>x.id===id)||coins[0]} function price(id){return market[id]?.usd||fallback[id]||0}
function fmt(n){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n<1?6:2}).format(n||0)}
function toast(title,sub,red=false){let t=document.createElement("div");t.className="toast";if(red)t.style.borderLeftColor="var(--red)";t.innerHTML=`<b>${title}</b><small>${sub}</small>`;document.body.append(t);setTimeout(()=>t.remove(),3500)}
function setupFX(){const p=document.querySelector("#particles");if(!p)return;for(let i=0;i<65;i++){let e=document.createElement("i");e.className="particle";e.style.left=Math.random()*100+"%";e.style.animationDuration=(8+Math.random()*16)+"s";e.style.animationDelay=(-Math.random()*20)+"s";e.style.opacity=.15+Math.random()*.6;p.append(e)}}
async function load(){try{let ids=coins.map(x=>x.id).join(",");let r=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${ids}&vs_currencies=usd&include_24hr_change=true`,{cache:"no-store"});if(!r.ok)throw 0;market=await r.json()}catch(e){if(!Object.keys(market).length)coins.forEach(x=>market[x.id]={usd:fallback[x.id],usd_24h_change:(Math.random()*8-4)})}coins.forEach(x=>{hist[x.id]??=[];hist[x.id].push(price(x.id));hist[x.id]=hist[x.id].slice(-80)});render();document.dispatchEvent(new Event("marketpulse"))}
function portfolioValue(){return state.cash+Object.entries(state.positions).reduce((s,[id,p])=>s+p.qty*price(id),0)}
function unrealized(){return Object.entries(state.positions).reduce((s,[id,p])=>s+(price(id)-p.avg)*p.qty,0)}
function invested(){return Object.values(state.positions).reduce((s,p)=>s+p.cost,0)}
function line(canvas,arr,markers=[],green=true){if(!canvas)return;let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;let x=canvas.getContext("2d");x.scale(d,d);let w=r.width,h=r.height;x.clearRect(0,0,w,h);x.strokeStyle="rgba(190,150,255,.1)";x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,h*i/5);x.lineTo(w,h*i/5);x.stroke()}let a=arr.length>1?arr:[price(selected)*.98,price(selected)];let min=Math.min(...a),max=Math.max(...a),span=max-min||1;x.beginPath();a.forEach((v,i)=>{let px=i/(a.length-1)*w,py=h-18-(v-min)/span*(h-36);i?x.lineTo(px,py):x.moveTo(px,py)});let grad=x.createLinearGradient(0,0,w,0);grad.addColorStop(0,green?"#35ed99":"#ff4d6d");grad.addColorStop(.5,green?"#8dffbe":"#ff93aa");grad.addColorStop(1,green?"#55e9ff":"#ff5277");x.strokeStyle=grad;x.lineWidth=2.6;x.shadowBlur=15;x.shadowColor=green?"#35ed99":"#ff5277";x.stroke();x.shadowBlur=0;markers.forEach(m=>{let i=Math.min(a.length-1,Math.max(0,m.i));let px=i/(a.length-1)*w,py=h-18-(a[i]-min)/span*(h-36);x.fillStyle=m.side==="buy"?"#39f59b":"#ff5277";x.beginPath();x.arc(px,py,6,0,Math.PI*2);x.fill();x.font="bold 9px system-ui";x.fillStyle="#fff";x.fillText(m.side==="buy"?"BUY":"SELL",px+9,py-8)})}
function miniCharts(){document.querySelectorAll("[data-mini]").forEach(el=>{let id=el.dataset.mini;let a=hist[id]||[price(id)];line(el,a,[],(a[a.length-1]||0)>=(a[0]||0))})}
function markersFor(id,a){let ts=state.trades.filter(t=>t.id===id).slice().reverse();return ts.map((t,i)=>({i:Math.round((i+1)*((a.length-1)/(ts.length+1))),side:t.side}))}
function render(){let page=document.body.dataset.page;document.querySelector("#topBalance")?.replaceChildren(document.createTextNode(fmt(state.cash)));if(page==="dashboard")dash();if(page==="markets")markets();if(page==="portfolio")portfolio();if(page==="challenges")challenges();if(page==="terminal")terminal();ticker();miniCharts()}
function ticker(){let el=document.querySelector("#ticker");if(!el)return;el.innerHTML=coins.slice(0,8).map(x=>{let p=price(x.id),ch=market[x.id]?.usd_24h_change||0;return `<span><b>${x.s}</b> ${fmt(p)} <i class="${ch>=0?"up":"down"}">${ch>=0?"+":""}${ch.toFixed(2)}%</i></span>`}).join("")}
function statHTML(){let pv=portfolioValue(),pl=unrealized();return `<div class="stats"><div class="stat"><label>Total portfolio</label><strong>${fmt(pv)}</strong><em class="${pl>=0?"up":"down"}">${pl>=0?"+":""}${fmt(pl)}</em></div><div class="stat"><label>Cash available</label><strong>${fmt(state.cash)}</strong><em>Ready to trade</em></div><div class="stat"><label>Invested</label><strong>${fmt(invested())}</strong><em>Cost basis</em></div><div class="stat"><label>Active positions</label><strong>${Object.keys(state.positions).length}</strong><em>${state.trades.length} filled trades</em></div></div>`}
function dash(){document.querySelector("#app").innerHTML=`<section class="hero"><div><div class="eyebrow">OVERVIEW / COMMAND CENTER</div><h1>Good trading<span class="blink">.</span></h1><p>Live public reference prices, persistent demo positions and execution markers — all connected to one local trading ledger.</p></div><div class="actions"><a class="btn" href="portfolio.html">Portfolio →</a><a class="btn primary" href="markets.html">Trade markets ↗</a></div></section>${statHTML()}<section class="two"><div class="panel"><div class="panelhead"><div><h2>Portfolio performance</h2><p>Account value</p></div><span class="live-tag">● LIVE</span></div><div class="bigchart"><canvas id="portfolioChart"></canvas></div></div><div class="panel"><div class="panelhead"><div><h2>Quick actions</h2><p>Control your demo account</p></div></div><div class="quickgrid"><button class="quick primaryq" onclick="location.href='markets.html'">↗ Trade crypto<small>Open markets</small></button><button class="quick" onclick="location.href='portfolio.html'">▤ Portfolio<small>Positions & P&L</small></button><button class="quick" onclick="addCash()">＋ Add balance<small>Demo USD</small></button><button class="quick" onclick="resetDemo()">↻ Reset demo<small>Start over</small></button></div><div class="notice">Demo mode only. No real money. Public prices are used as reference when the browser can reach the price service.</div></div></section><section class="panel"><div class="panelhead"><div><h2>Market pulse</h2><p>Major coins + meme coins</p></div><a class="textlink" href="markets.html">View all →</a></div><div id="preview" class="marketgrid"></div></section>`;document.querySelector("#preview").innerHTML=coins.slice(0,6).map(card).join("");let cv=document.querySelector("#portfolioChart");let pv=portfolioValue();line(cv,Array.from({length:50},(_,i)=>10000+(pv-10000)*i/49+Math.sin(i*.45)*18),[],pv>=10000)}
function card(x){let p=price(x.id),ch=market[x.id]?.usd_24h_change||0;return `<article class="market"><div class="coinrow"><div class="coin"><div class="coinlogo">${x.icon}</div><div><b>${x.name}</b><div class="symbol">${x.s} · ${x.cat}</div></div></div><span class="${ch>=0?"up":"down"}">${ch>=0?"+":""}${ch.toFixed(2)}%</span></div><div class="price">${fmt(p)}</div><div class="mini"><canvas data-mini="${x.id}"></canvas></div><div class="tradebuttons"><button class="btn buy" onclick="openTrade('${x.id}','buy')">Buy</button><button class="btn sell" onclick="openTrade('${x.id}','sell')">Sell</button></div></article>`}
function markets(){let q=(document.querySelector("#marketSearch")?.value||"").toLowerCase();let list=coins.filter(x=>(activeFilter==="All"||x.cat===activeFilter)&&(`${x.name}${x.s}`.toLowerCase().includes(q)));document.querySelector("#app").innerHTML=`<section class="hero"><div><div class="eyebrow">MARKETS / LIVE FEED</div><h1>Explore markets<span class="blink">.</span></h1><p>Major crypto and meme coins with visible animated charts and instant demo execution.</p></div><span class="live-tag">● LIVE</span></section><div class="searchwide">⌕ <input id="marketSearch" value="${q}" placeholder="Search Bitcoin, BTC, PEPE…"></div><div class="filters"><button class="filter ${activeFilter==="All"?"active":""}" onclick="filterMarkets('All')">All assets</button><button class="filter ${activeFilter==="Major"?"active":""}" onclick="filterMarkets('Major')">◈ Major</button><button class="filter ${activeFilter==="Meme"?"active":""}" onclick="filterMarkets('Meme')">🔥 Meme</button></div><div class="marketgrid">${list.map(card).join("")}</div>`;document.querySelector("#marketSearch").oninput=()=>markets()}
function filterMarkets(x){activeFilter=x;markets()}
function openTrade(id,s){selected=id;side=s;localStorage.setItem("kereos_selected",id);location.href="trade.html?coin="+id+"&side="+s}
function terminal(){let params=new URLSearchParams(location.search);selected=params.get("coin")||selected;side=params.get("side")||side;let x=c(selected),p=price(selected),pos=state.positions[selected]?.qty||0;document.querySelector("#app").innerHTML=`<section class="hero"><div><div class="eyebrow">TRADING TERMINAL / ${x.s}-USD</div><h1>${x.icon} ${x.name}</h1><p>Green/red live line, exact BUY/SELL markers and a real position-size sell control.</p></div><a class="btn" href="markets.html">← Markets</a></section><div class="terminal"><div class="panel terminalpanel"><div class="panelhead"><div><h2>${x.s} / USD · ${fmt(p)}</h2><p class="${(market[selected]?.usd_24h_change||0)>=0?"up":"down"}">${(market[selected]?.usd_24h_change||0)>=0?"+":""}${(market[selected]?.usd_24h_change||0).toFixed(2)}% 24h</p></div><div class="charttools"><button class="active">1H</button><button>4H</button><button>1D</button><button>1W</button></div></div><div class="tradechart"><canvas id="tradeChart"></canvas></div><div class="notice">🟢 BUY markers and 🔴 SELL markers are placed on the execution history. They remain after refresh.</div></div><div class="panel order"><div class="ordersides"><button class="${side==="buy"?"active buy":""}" onclick="side='buy';terminal()">BUY</button><button class="${side==="sell"?"active sell":""}" onclick="side='sell';terminal()">SELL</button></div><div class="field"><label>Market price <span>${fmt(p)}</span></label></div><div class="field"><label>Owned <span>${pos.toFixed(8)} ${x.s}</span></label></div><div class="field"><label>Quantity</label><input id="qty" class="input" type="number" min="0" step="any" placeholder="0.000000"></div>${side==="sell"?`<div class="percents">${[10,25,50,75,100].map(n=>`<button class="${sellPct===n?"active":""}" onclick="sellPct=${n};setSellQty()">${n}%</button>`).join("")}</div>`:""}<div class="summary"><div><span>Estimated value</span><b id="est">$0.00</b></div><div><span>Demo fee</span><b>0.10%</b></div><div><span>Cash</span><b>${fmt(state.cash)}</b></div></div><button id="execute" class="execute ${side}" onclick="execute()">${side==="buy"?"BUY":"SELL"} ${x.s}</button></div></div>`;document.querySelector("#qty").oninput=updateEst;if(side==="sell")setSellQty();updateEst();let a=hist[selected]||[];while(a.length<45){let base=p;a.unshift(base*(.985+Math.random()*.03))}line(document.querySelector("#tradeChart"),a,markersFor(selected,a),a[a.length-1]>=a[0])}
function setSellQty(){let q=state.positions[selected]?.qty||0;let el=document.querySelector("#qty");if(el)el.value=(q*sellPct/100).toFixed(8);updateEst()}
function updateEst(){let q=Number(document.querySelector("#qty")?.value||0),el=document.querySelector("#est");if(el)el.textContent=fmt(q*price(selected))}
function execute(){let q=Number(document.querySelector("#qty")?.value||0),p=price(selected),x=c(selected);if(!q||q<=0)return toast("Quantity required","Enter an amount first.",true);let fee=q*p*.001;if(side==="buy"){let total=q*p+fee;if(total>state.cash)return toast("Insufficient demo cash",`Need ${fmt(total)} · available ${fmt(state.cash)}`,true);let old=state.positions[selected]||{qty:0,cost:0,avg:p};old.cost+=q*p+fee;old.qty+=q;old.avg=old.cost/old.qty;state.positions[selected]=old;state.cash-=total}else{let old=state.positions[selected];if(!old||q>old.qty+1e-12)return toast("Not enough position",`You own ${old?.qty?.toFixed(8)||"0"} ${x.s}`,true);state.cash+=q*p-fee;old.qty-=q;old.cost=Math.max(0,old.cost-old.avg*q);if(old.qty<1e-10)delete state.positions[selected]}state.trades.unshift({id:selected,symbol:x.s,side,qty:q,price:p,value:q*p,fee,time:new Date().toISOString()});state.xp+=10;save();toast(`${side==="buy"?"BUY":"SELL"} EXECUTED`,`${q.toFixed(8)} ${x.s} @ ${fmt(p)}`);document.body.animate([{filter:"brightness(1)"},{filter:side==="buy"?"brightness(1.5)":"brightness(1.35)"},{filter:"brightness(1)"}],{duration:450});terminal()}
function portfolio(){let rows=Object.entries(state.positions);let pv=portfolioValue(),pl=unrealized();document.querySelector("#app").innerHTML=`<section class="hero"><div><div class="eyebrow">PORTFOLIO / CONTROL CENTER</div><h1>Your positions<span class="blink">.</span></h1><p>Every position below is linked to the same executed orders and reference prices as the terminal.</p></div><div class="actions"><button class="btn" onclick="resetDemo()">Reset</button><button class="btn primary" onclick="addCash()">＋ Add balance</button></div></section>${statHTML()}<section class="two"><div class="panel"><div class="panelhead"><div><h2>Portfolio performance</h2><p>Live mark-to-market</p></div></div><div class="bigchart"><canvas id="portfolioChart"></canvas></div></div><div class="panel"><div class="panelhead"><div><h2>Allocation</h2><p>Current position value</p></div></div><div class="allocation">${rows.length?rows.map(([id,p])=>{let v=p.qty*price(id),share=v/Math.max(1,pv)*100;return `<div class="allocrow"><b>${c(id).s}</b><div class="bar"><i style="width:${share}%"></i></div><span>${share.toFixed(1)}%</span></div>`}).join(""):`<div class="empty">No positions yet.</div>`}</div></div></section><section class="panel"><div class="panelhead"><div><h2>Holdings</h2><p>Choose 10%, 25%, 50%, 75% or 100% when selling.</p></div></div><div class="holdings">${rows.length?`<table class="table"><thead><tr><th>ASSET</th><th>QTY</th><th>AVG ENTRY</th><th>CURRENT</th><th>VALUE</th><th>P&L</th><th>ACTION</th></tr></thead><tbody>${rows.map(([id,p])=>{let x=c(id),cur=price(id),gain=(cur-p.avg)*p.qty;return `<tr><td><div class="coin"><div class="coinlogo">${x.icon}</div><b>${x.name}</b></div></td><td>${p.qty.toFixed(8)}</td><td>${fmt(p.avg)}</td><td>${fmt(cur)}</td><td>${fmt(cur*p.qty)}</td><td class="${gain>=0?"up":"down"}">${gain>=0?"+":""}${fmt(gain)}</td><td><button class="btn sell" onclick="openTrade('${id}','sell')">Sell</button></td></tr>`}).join("")}</tbody></table>`:`<div class="empty">No open positions. <a class="textlink" href="markets.html">Explore markets →</a></div>`}</div></section><section class="panel"><div class="panelhead"><div><h2>Trade history</h2><p>Exact execution prices</p></div></div><div class="history">${historyTable()}</div></section>`;let pvArr=Array.from({length:50},(_,i)=>10000+(pv-10000)*i/49+Math.sin(i*.4)*15);line(document.querySelector("#portfolioChart"),pvArr,[],pv>=10000)}
function historyTable(){if(!state.trades.length)return `<div class="empty">No filled orders yet.</div>`;return `<table class="table"><thead><tr><th>TYPE</th><th>ASSET</th><th>QTY</th><th>EXECUTION</th><th>VALUE</th><th>FEE</th><th>TIME</th></tr></thead><tbody>${state.trades.map(t=>`<tr><td class="${t.side==="buy"?"up":"down"}">${t.side.toUpperCase()}</td><td>${t.symbol}</td><td>${t.qty.toFixed(8)}</td><td>${fmt(t.price)}</td><td>${fmt(t.value)}</td><td>${fmt(t.fee)}</td><td>${new Date(t.time).toLocaleString()}</td></tr>`).join("")}</tbody></table>`}
function challenges(){let trades=state.trades.length,meme=state.trades.filter(t=>c(t.id).cat==="Meme").length,div=Object.keys(state.positions).length;let data=[["⚡","FIRST FLIGHT","Make your first trade",Math.min(100,trades?100:0),100],["🔥","MEME LORD","Trade 3 meme coins",Math.min(100,meme/3*100),300],["◈","DIVERSIFIER","Own 5 assets",Math.min(100,div/5*100),400],["🏆","10 TRADES","Complete 10 trades",Math.min(100,trades/10*100),250],["💎","DOUBLE UP","Grow $100 practice capital to $200",Math.min(100,Math.max(0,(portfolioValue()-100)/100*100)),500],["🌙","DIAMOND HANDS","Keep a position open",div?100:0,350]];document.querySelector("#app").innerHTML=`<section class="hero"><div><div class="eyebrow">CHALLENGES / PROGRESSION</div><h1>Level up<span class="blink">.</span></h1><p>Challenges are tied to your real demo activity. Earn XP as you trade.</p></div><div class="xpbox"><span>KEREOS XP</span><b>${state.xp}</b></div></section><div class="challengegrid">${data.map(x=>`<article class="panel challenge"><div style="font-size:24px">${x[0]}</div><h3>${x[1]}</h3><div class="muted">${x[2]}</div><div class="progress"><i style="width:${x[3]}%"></i></div><div style="display:flex;justify-content:space-between;margin-top:8px;font-size:10px"><span>${Math.round(x[3])}%</span><b>+${x[4]} XP</b></div></article>`).join("")}</div>`}
function addCash(){let n=Number(prompt("Add demo USD:","1000"));if(n>0){state.cash+=n;save();toast("Balance added",`${fmt(n)} added to demo cash.`);render()}}
function resetDemo(){if(confirm("Reset the Kereos demo account?")){state={cash:10000,positions:{},trades:[],xp:0};save();toast("Demo reset","Starting balance restored.");render()}}
function common(){setupFX();document.querySelector("#hamburger")?.addEventListener("click",()=>document.querySelector("#sidebar")?.classList.toggle("open"));document.querySelector("#globalSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter"){let q=e.target.value.toLowerCase(),x=coins.find(x=>(x.name+x.s).toLowerCase().includes(q));if(x)location.href="trade.html?coin="+x.id}})}
document.addEventListener("marketpulse",()=>{let page=document.body.dataset.page;if(page==="terminal")terminal();else render()});
setInterval(load,30000);common();load();
